### ISSUE TITLE
'ImageLocalizationDataset' is not defined

### ISSUE THREAD

**Issue by cbstryker** [lozuwa/impy#3]
I'm trying to use this example code:

```
import os
from impy import *

def main():
 # Define the path to images and annotations
 images_path = os.path.join(os.getcwd(), "train")
 annotations_path = os.path.join(os.getcwd(), "train-anno")
 # Define the name of the dataset
 dbName = "CarsDataset"
 # Create an object of ImageLocalizationDataset
 imda = ImageLocalizationDataset(imagesDirectory = images_path, annotationsDirectory = annotations_path, databaseName = dbName)
 # Reduce the dataset to smaller Rois of smaller ROIs of shape 1032x1032.
 images_output_path = os.path.join(os.getcwd(), "train-reduced")
 annotations_output_path = os.path.join(os.getcwd(), "train-reduced-anno")
 imda.reduceDatasetByRois(offset = [600, 600], outputImageDirectory = images_output_path, outputAnnotationDirectory = annotations_output_path)

if __name__ == "__main__":
 main()
```

But I keep getting this error

> Traceback (most recent call last):
>   File "resize.py", line 18, in <module>
>     main()
>   File "resize.py", line 11, in main
>     imda = ImageLocalizationDataset(imagesDirectory = images_path, annotationsDirectory = annotations_path, databaseName = dbName)
> NameError: name 'ImageLocalizationDataset' is not defined

Is there something I'm missing with the import process?

**Comment by imkhan1104** [comment]
Same here. Hope you can include the module soon

**Comment by lozuwa** [comment]
Hello @DANNALI35 @cbstryker 

I updated the documentation and tested the examples myself.
I also added a release with a .whl file so you can install Impy with pip. 

Let me know if there are more issues. 
Thanks
