### ISSUE TITLE
Do you try your augmentation on some public dataset?

### ISSUE THREAD

**Issue by qiang92** [lozuwa/impy#7]
First, thanks for your sharing.
Then, I saw in your example picture "Vertical flip". Objects are flipped vertically, and the overlapped parts of 
different objects return to its original direct. Both of the overlapped objects were destroyed which are hard to recognize visionally. 
I suggest you can keep the origin image when flipping objects rather than flipping objects in turns in the same image.
I want to ask if you do your augmentation on some public dataset like VOC07? 
Did it improve mAP score?

**Comment by lozuwa** [comment]
Hello, thanks for the suggestion. However I don't really get your claim. The original image is kept untouched, only the bounding box is affected.

Regarding the augmentation in some public dataset, I have not done that. If someone would like to contribute, then welcome and thanks.

**Comment by qiang92** [comment]
I'm sorry that I didn't make my words clear. 

I use the **red** and **blue** bbox in image below as a example.
![origin](https://user-images.githubusercontent.com/24382907/48325131-1d2c4900-e66f-11e8-9bc7-e6d260b9f624.png)

What I mean is that you **should** get image like this 
![origin_2_2](https://user-images.githubusercontent.com/24382907/48325072-d0e10900-e66e-11e8-910b-6a92bcd2e9f3.png)

**not** like this after vertical flipping
![origin_2](https://user-images.githubusercontent.com/24382907/48325079-db9b9e00-e66e-11e8-832d-e360b597f559.png)

You flipped the blue bbox first. Then you flipped the red bbox in the image containing the flipped blue bbox.
![origin_1](https://user-images.githubusercontent.com/24382907/48325235-988dfa80-e66f-11e8-8c06-5ee199f5692b.png)
You could remain the origin red bbox image before the blue bbox flips.
![origin_1_1](https://user-images.githubusercontent.com/24382907/48325279-ca9f5c80-e66f-11e8-9806-850080cba13b.png)

I think this may more realisitic for relative flipping.

**Comment by lozuwa** [comment]
Hey, that is a great idea! I actually did not think about that. Maybe you could do a PR. Otherwise, I will work on that some weekend. 
Thanks!!

**Comment by lozuwa** [comment]
If you have observations on other augmentation features, it would be awesome.
