### ISSUE TITLE
Can't run any way

### ISSUE THREAD

**Issue by tuansacer** [lozuwa/impy#8]
Dear @lozuwa 
I can't run any scripts in your repo with documents. Look like you had upgrade new version and not update document yet. I saw some class remove old name and run error. So now I don't know how to fix. Please update the document soon. Thanks.

**Comment by lozuwa** [comment]
Hey @tuansacer, can you show me the error that you are getting?

**Comment by lozuwa** [comment]
Hello @tuansacer, thanks for your interest in Impy. 

I have updated the documentation and tested it myself. I also added a release with a .whl file so you can install Impy with pip. 

Let me know if there are more issues. 
Thanks

**Comment by tuansacer** [comment]
yeah. when have time i will check. thanks so much
